#config_version=6
##! mode: popbmpr

#GORGAR

mode:
  start_events: start_mode_popbmpr
  stop_events: stop_mode_popbmpr
  priority: 350
  
event_player:
  mode_popbmpr_started: initialize_popbmpr
  
  
  
shot_groups:
  pop_bumper_score_change:
    shots: pop_bumper_1
    reset_events:
      pop_bumper_score_change_on_complete: 200ms
        
shots:
  pop_bumper_1:
    switch: s_pop_bumper_1
    profile: pop_flash_profile
  pop_bumper_2:
    switch: s_pop_bumper_2
    profile: pop_flash_profile
  pop_bumper_3:
    switch: s_pop_bumper_3
    profile: pop_flash_profile


    
shot_profiles:
  pop_flash_profile:
    states:
      - name: off
        show: off
      - name: on
        show: on
        

        
show_player:

###### ADD speed based on score
  mode_popbmpr_started:
    pop_cycle_show:
      loops: -1
      speed: 2
      priority: 10
      show_tokens:
        led_1: led_pop_lwr_1, led_pop_lf_3, led_pop_rt_6
        led_2: led_pop_lwr_2, led_pop_lf_4, led_pop_rt_7
        led_3: led_pop_lwr_3, led_pop_lf_5, led_pop_rt_8
        led_4: led_pop_lwr_4, led_pop_lf_6, led_pop_rt_1
        led_5: led_pop_lwr_5, led_pop_lf_7, led_pop_rt_2
        led_6: led_pop_lwr_6, led_pop_lf_8, led_pop_rt_3
        led_7: led_pop_lwr_7, led_pop_lf_1, led_pop_rt_4
        led_8: led_pop_lwr_8, led_pop_lf_2, led_pop_rt_5
        color1: red
        color2: off
        
  player_score{value>=10000}:
    pop_cycle_show:
      action: stop
    pop_cycle_show_2:
      loops: -1
      speed: 4
      priority: 10
      show_tokens:
        led_1: led_pop_lwr_1, led_pop_lf_3, led_pop_rt_6
        led_2: led_pop_lwr_2, led_pop_lf_4, led_pop_rt_7
        led_3: led_pop_lwr_3, led_pop_lf_5, led_pop_rt_8
        led_4: led_pop_lwr_4, led_pop_lf_6, led_pop_rt_1
        led_5: led_pop_lwr_5, led_pop_lf_7, led_pop_rt_2
        led_6: led_pop_lwr_6, led_pop_lf_8, led_pop_rt_3
        led_7: led_pop_lwr_7, led_pop_lf_1, led_pop_rt_4
        led_8: led_pop_lwr_8, led_pop_lf_2, led_pop_rt_5
        color1: red
        color2: off
        
  player_score{value>=30000}:
    pop_cycle_show_2:
      action: stop
    pop_cycle_show:
      loops: -1
      speed: 6
      priority: 10
      show_tokens:
        led_1: led_pop_lwr_1, led_pop_lf_3, led_pop_rt_6
        led_2: led_pop_lwr_2, led_pop_lf_4, led_pop_rt_7
        led_3: led_pop_lwr_3, led_pop_lf_5, led_pop_rt_8
        led_4: led_pop_lwr_4, led_pop_lf_6, led_pop_rt_1
        led_5: led_pop_lwr_5, led_pop_lf_7, led_pop_rt_2
        led_6: led_pop_lwr_6, led_pop_lf_8, led_pop_rt_3
        led_7: led_pop_lwr_7, led_pop_lf_1, led_pop_rt_4
        led_8: led_pop_lwr_8, led_pop_lf_2, led_pop_rt_5
        color1: red
        color2: off
        
  player_score{value>=60000}:
    pop_cycle_show:
      action: stop
    pop_cycle_show_2:
      loops: -1
      speed: 8
      priority: 10
      show_tokens:
        led_1: led_pop_lwr_1, led_pop_lf_3, led_pop_rt_6
        led_2: led_pop_lwr_2, led_pop_lf_4, led_pop_rt_7
        led_3: led_pop_lwr_3, led_pop_lf_5, led_pop_rt_8
        led_4: led_pop_lwr_4, led_pop_lf_6, led_pop_rt_1
        led_5: led_pop_lwr_5, led_pop_lf_7, led_pop_rt_2
        led_6: led_pop_lwr_6, led_pop_lf_8, led_pop_rt_3
        led_7: led_pop_lwr_7, led_pop_lf_1, led_pop_rt_4
        led_8: led_pop_lwr_8, led_pop_lf_2, led_pop_rt_5
        color1: red
        color2: off
        
  player_score{value>=90000}:
    pop_cycle_show_2:
      action: stop
    pop_cycle_show:
      loops: -1
      speed: 10
      priority: 10
      show_tokens:
        led_1: led_pop_lwr_1, led_pop_lf_3, led_pop_rt_6
        led_2: led_pop_lwr_2, led_pop_lf_4, led_pop_rt_7
        led_3: led_pop_lwr_3, led_pop_lf_5, led_pop_rt_8
        led_4: led_pop_lwr_4, led_pop_lf_6, led_pop_rt_1
        led_5: led_pop_lwr_5, led_pop_lf_7, led_pop_rt_2
        led_6: led_pop_lwr_6, led_pop_lf_8, led_pop_rt_3
        led_7: led_pop_lwr_7, led_pop_lf_1, led_pop_rt_4
        led_8: led_pop_lwr_8, led_pop_lf_2, led_pop_rt_5
        color1: red
        color2: off
        
  player_score{value>=120000}:
    pop_cycle_show:
      action: stop
    pop_cycle_show_2:
      loops: -1
      speed: 12
      priority: 10
      show_tokens:
        led_1: led_pop_lwr_1, led_pop_lf_3, led_pop_rt_6
        led_2: led_pop_lwr_2, led_pop_lf_4, led_pop_rt_7
        led_3: led_pop_lwr_3, led_pop_lf_5, led_pop_rt_8
        led_4: led_pop_lwr_4, led_pop_lf_6, led_pop_rt_1
        led_5: led_pop_lwr_5, led_pop_lf_7, led_pop_rt_2
        led_6: led_pop_lwr_6, led_pop_lf_8, led_pop_rt_3
        led_7: led_pop_lwr_7, led_pop_lf_1, led_pop_rt_4
        led_8: led_pop_lwr_8, led_pop_lf_2, led_pop_rt_5
        color1: red
        color2: off
        
  player_score{value>=150000}:
    pop_cycle_show_2:
      action: stop
    pop_cycle_show:
      loops: -1
      speed: 14
      priority: 10
      show_tokens:
        led_1: led_pop_lwr_1, led_pop_lf_3, led_pop_rt_6
        led_2: led_pop_lwr_2, led_pop_lf_4, led_pop_rt_7
        led_3: led_pop_lwr_3, led_pop_lf_5, led_pop_rt_8
        led_4: led_pop_lwr_4, led_pop_lf_6, led_pop_rt_1
        led_5: led_pop_lwr_5, led_pop_lf_7, led_pop_rt_2
        led_6: led_pop_lwr_6, led_pop_lf_8, led_pop_rt_3
        led_7: led_pop_lwr_7, led_pop_lf_1, led_pop_rt_4
        led_8: led_pop_lwr_8, led_pop_lf_2, led_pop_rt_5
        color1: red
        color2: off
        
  player_score{value>=180000}:
    pop_cycle_show:
      action: stop
    pop_cycle_show_2:
      loops: -1
      speed: 16
      priority: 10
      show_tokens:
        led_1: led_pop_lwr_1, led_pop_lf_3, led_pop_rt_6
        led_2: led_pop_lwr_2, led_pop_lf_4, led_pop_rt_7
        led_3: led_pop_lwr_3, led_pop_lf_5, led_pop_rt_8
        led_4: led_pop_lwr_4, led_pop_lf_6, led_pop_rt_1
        led_5: led_pop_lwr_5, led_pop_lf_7, led_pop_rt_2
        led_6: led_pop_lwr_6, led_pop_lf_8, led_pop_rt_3
        led_7: led_pop_lwr_7, led_pop_lf_1, led_pop_rt_4
        led_8: led_pop_lwr_8, led_pop_lf_2, led_pop_rt_5
        color1: red
        color2: off
        
  player_score{value>=210000}:
    pop_cycle_show_2:
      action: stop
    pop_cycle_show:
      loops: -1
      speed: 18
      priority: 10
      show_tokens:
        led_1: led_pop_lwr_1, led_pop_lf_3, led_pop_rt_6
        led_2: led_pop_lwr_2, led_pop_lf_4, led_pop_rt_7
        led_3: led_pop_lwr_3, led_pop_lf_5, led_pop_rt_8
        led_4: led_pop_lwr_4, led_pop_lf_6, led_pop_rt_1
        led_5: led_pop_lwr_5, led_pop_lf_7, led_pop_rt_2
        led_6: led_pop_lwr_6, led_pop_lf_8, led_pop_rt_3
        led_7: led_pop_lwr_7, led_pop_lf_1, led_pop_rt_4
        led_8: led_pop_lwr_8, led_pop_lf_2, led_pop_rt_5
        color1: red
        color2: off
        
  player_score{value>=240000}:
    pop_cycle_show:
      action: stop
    pop_cycle_show_2:
      loops: -1
      speed: 19
      priority: 10
      show_tokens:
        led_1: led_pop_lwr_1, led_pop_lf_3, led_pop_rt_6
        led_2: led_pop_lwr_2, led_pop_lf_4, led_pop_rt_7
        led_3: led_pop_lwr_3, led_pop_lf_5, led_pop_rt_8
        led_4: led_pop_lwr_4, led_pop_lf_6, led_pop_rt_1
        led_5: led_pop_lwr_5, led_pop_lf_7, led_pop_rt_2
        led_6: led_pop_lwr_6, led_pop_lf_8, led_pop_rt_3
        led_7: led_pop_lwr_7, led_pop_lf_1, led_pop_rt_4
        led_8: led_pop_lwr_8, led_pop_lf_2, led_pop_rt_5
        color1: red
        color2: off
        
  player_score{value>=270000}:
    pop_cycle_show_2:
      action: stop
    pop_cycle_show:
      loops: -1
      speed: 20
      priority: 10
      show_tokens:
        led_1: led_pop_lwr_1, led_pop_lf_3, led_pop_rt_6
        led_2: led_pop_lwr_2, led_pop_lf_4, led_pop_rt_7
        led_3: led_pop_lwr_3, led_pop_lf_5, led_pop_rt_8
        led_4: led_pop_lwr_4, led_pop_lf_6, led_pop_rt_1
        led_5: led_pop_lwr_5, led_pop_lf_7, led_pop_rt_2
        led_6: led_pop_lwr_6, led_pop_lf_8, led_pop_rt_3
        led_7: led_pop_lwr_7, led_pop_lf_1, led_pop_rt_4
        led_8: led_pop_lwr_8, led_pop_lf_2, led_pop_rt_5
        color1: red
        color2: off
        
  player_score{value>=300000}:
    pop_cycle_show:
      action: stop
    pop_cycle_show_3:
      loops: -1
      speed: 4
      priority: 10
      show_tokens:
        led: led_pop
        color1: red
        color2: off
        color3: blue
        
        
  s_pop_bumper_1_active:
    color_cycle_show:
      loops: 0
      speed: 11
      priority: 20
      show_tokens:
        led: led_lf_pop 
        color1: white
        color2: off
        
  s_pop_bumper_2_active:
    color_cycle_show:
      loops: 0
      speed: 11
      priority: 20
      show_tokens:
        led: led_rt_pop 
        color1: white
        color2: off
        
  s_pop_bumper_3_active:
    color_cycle_show:
      loops: 0
      speed: 11
      priority: 20
      show_tokens:
        led: led_lwr_pop 
        color1: white
        color2: off
        
  lwr_drop_bank_pop_bns_1:
    color_cycle_show:
      loops: -1
      speed: 11
      priority: 21
      show_tokens:
        led: led_lwr_pop 
        color1: white
        color2: white
  lwr_drop_bank_pop_bns_2:
    color_cycle_show:
      loops: -1
      speed: 11
      priority: 21
      show_tokens:
        led: led_lwr_pop, led_lf_pop 
        color1: white
        color2: white
  lwr_drop_bank_pop_bns_3:
    color_cycle_show:
      loops: -1
      speed: 11
      priority: 21
      show_tokens:
        led: led_lwr_pop, led_lf_pop, led_rt_pop 
        color1: white
        color2: white

light_player:

  lwr_drop_bank_pop_bns_1:    
        led_lwr_pop:
            color: white
            fade: 500ms  
  lwr_drop_bank_pop_bns_2:    
        led_lf_pop:
            color: white
            fade: 500ms   
  lwr_drop_bank_pop_bns_3:    
        led_rt_pop:
            color: white
            fade: 500ms            

  
              
variable_player:
      
  pop_bumper_1_hit:
    score: 100 * current_player.pf_multiplier * current_player.pop_1_multiplier
  pop_bumper_2_hit:
    score: 100 * current_player.pf_multiplier * current_player.pop_2_multiplier
  pop_bumper_3_hit:
    score: 100 * current_player.pf_multiplier * current_player.pop_3_multiplier
  s_left_sling_shot_active:
    score: 100 * current_player.pf_multiplier
  s_right_sling_shot_active:
    score: 100 * current_player.pf_multiplier
    


  mode_popbmpr_started:
    pop_1_multiplier:
      int: 1
      action: set
    pop_2_multiplier:
      int: 1
      action: set
    pop_3_multiplier:
      int: 1
      action: set
      
  lwr_drop_bank_pop_bns_1:
    pop_1_multiplier:
      int: 10
      action: set
    pop_2_multiplier:
      int: 10
      action: set
    pop_3_multiplier:
      int: 10
      action: set
    
    
    
    
