#config_version=6

#Gorgar

#coil numbers are labelled in silkscreen on the board

  #There are multiple ways to configure flippers, use the one that
  #  matches your hardware
  
coils:
    c_pop_bmp_3:
        number: 0-0-0
        tags: pop
        default_pulse_ms: 17
    c_shooter_launch:
        number: 0-0-1
        tags: launch_kicker
        default_pulse_ms: 15
    c_trough_eject:
        number: 0-0-2
        tags: trough
        default_pulse_ms: 15              
    c_slingshot_right:
        number: 0-0-3
        tags: slingshot
        default_pulse_ms: 10
        default_recycle: true
        platform_settings:
            recycle_factor: 3
    c_slingshot_left:
        number: 0-0-4
        tags: slingshot
        default_pulse_ms: 10
        default_recycle: true
        platform_settings:
            recycle_factor: 3
    c_saucer_left:
        number: 0-0-5
        tags: lower_trap
        default_pulse_ms: 20    
    c_drop_target_lwr:
        number: 0-0-6
        tags: lwr_drop_target
        default_pulse_ms: 25   
    c_drop_target_upr:
        number: 0-0-7
        tags: upr_drop_target
        default_pulse_ms: 25   
    c_kickback:
        number: 0-0-11
        tags: kickback
        default_pulse_ms: 15        
    c_pop_bmp_2:
        number: 0-0-12
        tags: pop
        default_pulse_ms: 17
    c_pop_bmp_1:
        number: 0-0-13
        tags: pop
        default_pulse_ms: 17
    c_magna_left:
        number: 0-0-14
        tags: magna_save_coil_left
        default_pulse_ms: 17
        default_hold_power: 0.575
    c_bell:
        number: 0-0-15
        tags: bell
        default_pulse_ms: 10

    c_flipper_left_main:
        number: 1-0-3
        default_pulse_ms: 18
    c_flipper_left_hold:
        number: 1-0-4
        allow_enable: true
        default_hold_power: 0.8
        default_pulse_ms: 11
    c_flipper_right_main:
        number: 1-0-1
        default_pulse_ms: 18
    c_flipper_right_hold:
        number: 1-0-2
        allow_enable: true
        default_hold_power: 0.8
        default_pulse_ms: 11
    
    
    
        
### Satellite Board  ### Coils are 48 VDC  ###

  
    #c_magna_left:
    #   number: 3-0-1
    #    tags: magna_save_coil_left
    #    default_pulse_ms: 10
    #    default_hold_power: 0.375

        
    
    #led_flasher_1:
    #    number: 3-0-5
    #    allow_enable: true
    #    default_hold_power: 0.2
    #    default_pulse_ms: 5
    #led_flasher_2:
    #    number: 3-0-6
    #    allow_enable: true
    #    default_hold_power: 0.2
    #    default_pulse_ms: 5
        