#config_version=6


    
slides:
    welcome_slide:
        widgets:
        - type: text
          text: PINBALL!
          font_size: 100
          color: red
        #- type: rectangle
          #width: 240
          #height: 60
